import "tailwindcss/tailwind.css";
import { Metadata } from "next";
import Header from "../components/partials/Header";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="font-display bg-gray-800 leading-normal antialiased" lang="en">
      <body>
        <main className="py-4">{children}</main>
      </body>
    </html>
  );
}
